steps:
  # Check for typos
  typos:
    image: fish
    commands:
      - distrobox enter archlinux-latest
      - typos
    failure: ignore
    when:
      event: [push, pull_request, manual]

  # Check website build
  check:
    image: alpine:edge
    commands:
      - distrobox enter archlinux-latest
      - zola check
    when:
      event: [pull_request]

  # Build and publish website
  build:
    image: alpine:edge
    commands:
      - distrobox enter archlinux-latest
      - zola build --output-dir /srv/http/daudix
    when:
      event: [push, manual]
