# Exclude page pipeline to be run on "pages" branch
when:
  branch:
    exclude: pages

# Recursive cloning is used to fully clone the themes given as Git submodules
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  update:
    image: alpine/git
    commands:
      - git submodule update --init --recursive
      - git submodule foreach --recursive "git fetch origin && git reset --hard origin/HEAD || :"
      - git submodule update --remote --merge || git pull --allow-unrelated-histories
    when:
      event: push

  build:
    image: alpine
    commands:
      - apk add zola
      - zola build
    when:
      event: [ pull_request, push ]

  publish:
    image: bitnami/git
    # Must be set in Woodpecker configuration
    secrets: [ mail, codeberg_token ]
    commands:
      # Save .domains
      # - domains=$(cat .domains)
      # Git configuration
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      # Push Updated Duckquill
      - git add --all
      - git commit -m "Updated Duckquill"
      - git push
      # Clone output branch
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      # Enter output branch folder
      - cd $CI_REPO_NAME
      # Remove old files
      - git rm -r "*"
      # Copy build step output
      - cp -ar ../public/. .
      # Add .domains back
      # - echo $domains > .domains
      # Commit and push all static files with source commit SHA
      - git add --all
      - git commit -m "Woodpecker CI ${CI_COMMIT_SHA} [SKIP CI]"
      - git push
    when:
      event: push
