steps:
  # Check for typos
  typos:
    image: fish
    commands:
      - $HOME/.local/bin/typos
    failure: ignore
    when:
      event: [push, pull_request, manual]

  # Check website build
  check:
    image: fish
    commands:
      - $HOME/.local/bin/zola check
    when:
      event: [pull_request]

  # Build and publish website
  build:
    image: fish
    commands:
      - $HOME/.local/bin/zola build --output-dir /srv/http/daudix --force
    when:
      event: [push, manual]
