# Site settings
title: Daudix's Blog
baseurl: "/blog" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for buidling absolute URIs
                                 # for metadata header
url: "https://daudix.undo.it"   # the base hostname & protocol for your site
sourceurl: "https://github.com/daudix-UFO/blog" # "edit this website" link in the footer
description: "Description of the OS Component website."
issuesurl: "https://github.com/daudix-UFO/blog/issues" # issue tracker for website
permalink: /:title/
primary-color: "#c061cb" #used in ios theme. further color customization in style.css  

# Build settings
markdown: kramdown
