# Site settings
title: Daudix's Blog
baseurl: "/blog" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for building absolute URIs
                                 # for metadata header
url: "https://daudix-ufo.codeberg.page"   # the base hostname & protocol for your site
sourceurl: "https://codeberg.org/daudix-UFO/blog-source" # "edit this website" link in the footer
hosting: "Codeberg" # the hosting of your site, e.g Codeberg
description: "Daudix UFO's blog."
issuesurl: "https://codeberg.org/daudix-UFO/blog-source/issues" # issue tracker for website
permalink: /:title/
primary-color: "#c061cb" #used in iOS theme. further color customization in style.css

# Mastodon-powered commenting. See https://github.com/cassidyjames/cassidyjames.github.io/blob/main/_config.yaml#L33
comments:
  host: mstdn.social
  username: Daudix

# Build settings
markdown: kramdown
timezone: UTC
exclude: [Gemfile, Gemfile.lock, Dockerfile, local.sh, rename.sh, README.md]

feed:
  tags:
    path: "feed/tags/"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-toc
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
      author: "Daudix_UFO"
      destination: "posts"