# Site settings
title: Daudix's Blog
url: "https://daudix-ufo.codeberg.page" # the base hostname & protocol for your site
sourceurl: "https://codeberg.org/daudix-UFO/blog-source" # "edit this website" link in the footer
hosting: "Codeberg" # the hosting of your site, e.g Codeberg
description: "Daudix UFO's blog."
issuesurl: "https://codeberg.org/daudix-UFO/blog-source/issues" # issue tracker for website
permalink: /:title/
primary-color: "#c061cb" # used in iOS theme. further color customization in _sass/variables.scss

# Mastodon-powered commenting.
# See https://github.com/cassidyjames/cassidyjames.github.io/blob/main/_config.yaml#L31-L70
comments:
  host: mstdn.social
  username: Daudix
  token: jTNX9pAV8XEPBby0cPWF6CmGY60kkIy4vidggfxXmoQ

# Build settings
markdown: kramdown
timezone: UTC
exclude: [Gemfile, Gemfile.lock, Dockerfile, local.sh, rename.sh, README.md]

compress_html:
  blanklines: true

feed:
  tags:
    path: "feed/tags/"
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-loading-lazy
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-toc
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
      author: "Daudix_UFO"
      destination: "posts"
