[build]
publish = "public"
command = "git submodule update --init --recursive && zola build"

[build.environment]
ZOLA_VERSION = "0.20.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
