[build]
publish = "public"
command = "git submodule update --init --recursive && zola build"

[build.environment]
ZOLA_VERSION = "0.20.0"

[context.deploy-preview]
command = "git submodule update --init --recursive && zola build --base-url $DEPLOY_PRIME_URL"

[[redirects]]
from = "/api/*"
to = "https://cloud.umami.is/:splat"
status = 200
force = true

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins.inputs.audits]]
path = "home"
