[build]
publish = "public"
command = "git submodule update --init --recursive && zola build"

[build.environment]
ZOLA_VERSION = "0.21.0"

[context.deploy-preview]
command = "git submodule update --init --recursive && zola build --base-url $DEPLOY_PRIME_URL"

[[redirects]]
from = "/api/*"
to = "https://cloud.umami.is/:splat"
status = 200
force = true

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins.inputs.audits]]
path = "home"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=63072000; includeSubdomains"
