[phases.setup]
nixPkgs = ["zola"]
nixpkgsArchive = "97d60f8918c8a3c46316682fdfc6b8bcf2ddc3c4"

[phases.build]
cmds = ["zola build"]

[environment]
ZOLA_VERSION = "0.21.0"

[[nixpacks.included_files]]
paths = ["/public"]
