name: "Deploy"

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: "Vercel Deploy"
    steps:
      - name: "Checkout"
        uses: "https://code.forgejo.org/actions/checkout@v4"
      - name: "Install Vercel CLI"
        run: npm install --global vercel@latest
      - name: "Deploy"
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
