name: "Preview"

on:
  pull_request:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  preview:
    name: "Preview"
    steps:
      - name: "Checkout"
        uses: "https://code.forgejo.org/actions/checkout@v4"
      - name: "Install Vercel CLI"
        run: npm install --global vercel@latest
      - name: "Preview"
        run: vercel deploy --token=$VERCEL_TOKEN
