backend:
  name: git-gateway
  branch: main

media_folder: static/media
public_folder: /media

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    view_filters:
    - label: Drafts
      field: draft
      pattern: true
    media_folder: ""
    public_folder: ""
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Authors
        name: authors
        widget: list
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
        required: false
      - label: Updated
        name: updated
        widget: datetime
        format: "YYYY-MM-DD"
        required: false
      - label: Tags
        name: taxonomies.tags
        widget: list
        default: []
      - label: Categories
        name: taxonomies.categories
        widget: list
        default: []
      - label: Accent Color
        name: extra.accent_color
        widget: list
        default: []
        max: 2
        field:
          label: Color
          name: color
          widget: color
      - label: Banner
        name: extra.banner
        widget: image
        allow_multiple: false
        choose_url: false
        required: false
      - label: Pixel-art Banner
        name: extra.banner_pixels
        widget: boolean
        required: false
        default: false
      - label: Alerts
        name: extra
        widget: object
        required: false
        fields:
          - label: Archive
            name: archive
            widget: markdown
            required: false
          - label: Trigger
            name: trigger
            widget: markdown
            required: false
          - label: Disclaimer
            name: disclaimer
            widget: markdown
            required: false
      - label: Stylesheets
        name: extra.styles
        widget: list
        required: false
        default: []
      - label: Fediverse
        name: extra.fediverse
        widget: object
        required: false
        fields:
          - label: Host
            name: host
            widget: string
            required: false
          - label: User
            name: user
            widget: string
            required: false
          - label: ID
            name: id
            widget: string
            required: false
      - label: Body
        name: body
        widget: markdown

  - label: Nanolog
    name: nanolog
    folder: content/nanolog
    create: true
    path: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
      - label: Updated
        name: updated
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
        required: false
      - label: Body
        name: body
        widget: markdown
