backend:
  name: git-gateway
  branch: main

media_folder: static/media
public_folder: /media

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    format: toml-frontmatter
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    media_folder: "."
    public_folder: "."
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
        required: false
      - label: Authors
        name: authors
        widget: list
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
        required: false
      - label: Updated
        name: updated
        widget: datetime
        format: "YYYY-MM-DD"
        required: false
      - label: Tags
        name: taxonomies.tags
        widget: list
        default: []
      - label: Categories
        name: taxonomies.categories
        widget: list
        default: []
      - label: Extra
        name: extra
        widget: object
        collapsed: true
        required: false
        fields:
          - label: Stylesheets
            name: styles
            widget: list
            required: false
            default: []

          - label: Accent Color
            name: accent_color
            widget: list
            required: false
            default: []
            max: 2
            field:
              label: Color
              name: color
              widget: string

          - label: Banner
            name: banner
            widget: image
            allow_multiple: false
            choose_url: false
            required: false

          - label: Pixel-art Banner
            name: banner_pixels
            widget: boolean
            required: false
            default: false

          - label: Alerts
            name: alerts
            widget: object
            collapsed: true
            required: false
            fields:
              - label: Archive
                name: archive
                widget: markdown
                required: false
              - label: Trigger
                name: trigger
                widget: markdown
                required: false
              - label: Disclaimer
                name: disclaimer
                widget: markdown
                required: false

          - label: Fediverse
            name: fediverse
            widget: object
            collapsed: true
            required: false
            fields:
              - label: Host
                name: host
                widget: string
                required: false
              - label: User
                name: user
                widget: string
                required: false
              - label: ID
                name: id
                widget: string
                required: false
      - label: Body
        name: body
        widget: markdown

  - label: Nanolog
    name: nanolog
    folder: content/nanolog
    create: true
    format: toml-frontmatter
    path: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
      - label: Updated
        name: updated
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ss[Z]"
        required: false
      - label: Body
        name: body
        widget: markdown
