# Exclude page pipeline to be run on "pages" branch
when:
  event: manual
  branch:
    exclude: pages

# Recursive cloning is used to fully clone the themes given as Git submodules
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  # Update Git Submodule
  update:
    image: alpine/git
    commands:
      - git submodule update --init --recursive
      - git submodule foreach --recursive 'git fetch origin && git reset --hard origin/HEAD || :'
      - git submodule update --remote --merge || git pull --allow-unrelated-histories
    when:
      event: [ manual ]

  # Continue with the rest of your build steps
  publish:
    image: bitnami/git
    secrets: [mail, codeberg_token]
    commands:
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git add --all
      - git commit -m "Updated Duckquill"
      - git remote set-url origin https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git
      - git push --set-upstream origin main